version: '3.8'

services:
  db:
    image: postgres:15
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5416:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  service:
    build:
      context: ./Service/Service
    container_name: my_dotnet_service
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    ports:
      - "5109:8080"
    depends_on:
      - db
    networks:
      - app-network

  nginx:
    build:
      context: ./Clients
    container_name: my_nginx
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - service
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
